---
beet_domain: "slim.local"
beet_root: "{{ beet_base }}/docroot"
role_path: "{{ beet_home }}/provisioning/ansible/roles/beetboxvm.slim"

beet_project: slim
slim_create_new: yes
slim_add_example: yes
slim_add_htaccess: yes
